title: Chef Sugar
description: Chef Sugar is a Gem & Chef Recipe that includes series of helpful sugar of the Chef core and other resources to make a cleaner, more lean recipd DSL, enforce DRY principles, and make writing Chef recipes an awesome experience!
google_analytics: UA-12012976-11
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
